Controllers/FlashCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoMVC.Classes;
using DemoMVC.Respiratory;
using DemoMVC.Models;

namespace DemoMVC.Controllers
{
    public class FlashCardController : Controller
    {
        private IDrugCardsRepository<Drug> cardRepository { get; set; }

        public FlashCardController(IDrugCardsRepository<Drug> repository)
        {
            this.cardRepository = repository;
        }

        // GET: FlashCard
        public ActionResult Indexs()
        {
            List<Drug> myDrugList =  this.cardRepository.GetAllDrugs();
            //List<Drug> myDrugList = new DrugCardsRepository().GetAllDrugs();
            FlashDrugSetModel setModel = new FlashDrugSetModel();
            setModel.userDrugInfoArray = MyRandomizeStringArray.RandomizeStringsDurstenfeld( myDrugList.Select(x => x.DrugBrand).ToArray() );
            setModel.currentDisplayDrug = myDrugList.Where(x => x.DrugBrand.ToLower() == setModel.userDrugInfoArray[0].ToLower()).First();
            setModel.currentArrayIndex = 0;

            IEnumerable<string> myDrugTypes = new DrugCardsRepository().GetAllPossibleTypes();

            ViewBag.myDrugTypes = myDrugTypes;

            return View(setModel);
        }

        public JsonResult GetSearchDrugs(string term)
        {
            List<string> myDrugString = MySearchPossibleDrugs(term);

            return Json(myDrugString, JsonRequestBehavior.AllowGet);
        }

        [NonAction]
        private static List<string> MySearchPossibleDrugs(string term)
        {
            List<Drug> myDrugList = new DrugCardsRepository().GetAllDrugs();

            List<Drug> myDrugListBrand = myDrugList.Where(item => item.DrugBrand.ToLower().Contains(term.ToLower())).ToList<Drug>();
            List<Drug> myDrugListGeneric = myDrugList.Where(item => item.DrugBrand.ToLower().Contains(term.ToLower())).ToList<Drug>();

            List<string> myDrugString = myDrugListBrand.Select(x => x.DrugBrand).ToList();
            myDrugString.AddRange(myDrugListGeneric.Select(x => x.DrugGeneric).ToList());
            return myDrugString;
        }

        public PartialViewResult DrugSearch(string term)
        {
            List<string> myDrugString = MySearchPossibleDrugs(term);
            SearchDrugsModel searchDrugsModel = new SearchDrugsModel();
            searchDrugsModel.searchDrugsResult = myDrugString;

            return PartialView("_SearchDrugsResult", searchDrugsModel);
        }

        [NonAction]
        private static List<string> MyTypePossibleDrugs(string searchTerm)
        {
            List<Drug> myDrugList = new DrugCardsRepository().GetAllDrugs();

            List<Drug> myDrugListBrand = myDrugList.Where(item => item.DrugType.ToLower().Contains(searchTerm.ToLower())).ToList<Drug>();
            List<string> myDrugString = myDrugListBrand.Select(x => x.DrugBrand).ToList();

            return myDrugString;
        }

        public PartialViewResult DrugTypeSearch(string drugTypeSearch)
        {
            List<string> myDrugString = MyTypePossibleDrugs(drugTypeSearch);
            SearchDrugsModel searchDrugsModel = new SearchDrugsModel();
            searchDrugsModel.searchDrugsResult = myDrugString;

            return PartialView("_SearchDrugsResult", searchDrugsModel);
        }

        //[ValidateAntiForgeryToken]
        //http://www.leniel.net/2013/09/detecting-fixing-ajax-beginform-partial-view-stale-data.html#sthash.agYs0tDH.dpbs
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public PartialViewResult FlashMyCard(FlashDrugSetModel drugSetModel,string submit)
        {
            if (submit.ToLower() == "next")
            {
                if ((drugSetModel.userDrugInfoArray.Length > 1) && (drugSetModel.currentArrayIndex < drugSetModel.userDrugInfoArray.Length-1))
                {
                    drugSetModel.currentArrayIndex = drugSetModel.currentArrayIndex + 1;
                }
            }
            else if(submit.ToLower()=="previous")
            {
                if ((drugSetModel.userDrugInfoArray.Length > 0) && (drugSetModel.currentArrayIndex > 0))
                {
                    drugSetModel.currentArrayIndex = drugSetModel.currentArrayIndex - 1;
                }

            }

            List<Drug> myDrugSearch = new DrugCardsRepository().GetDrugBrand(drugSetModel.userDrugInfoArray[drugSetModel.currentArrayIndex]);

            if (myDrugSearch.Count > 0)
            {
                drugSetModel.currentDisplayDrug = myDrugSearch.First();
            }
            else
            {
                myDrugSearch = new DrugCardsRepository().GetDrugGeneric(drugSetModel.userDrugInfoArray[drugSetModel.currentArrayIndex]);
                drugSetModel.currentDisplayDrug = myDrugSearch.First();
            }

            ModelState.Clear();

            return PartialView("_FlashMyCard", drugSetModel);
        }

        public PartialViewResult FlashACard(string wantedDisplayDrug)
        {
            FlashDrugSetModel drugSetModel = new FlashDrugSetModel();

            List<Drug> myBrandSearch = new DrugCardsRepository().GetDrugBrand(wantedDisplayDrug);
            List<Drug> myGenericSearch = new DrugCardsRepository().GetDrugGeneric(wantedDisplayDrug);

            drugSetModel.currentArrayIndex = 0;
            List<string> resultInfo = new List<string>();

            if (myBrandSearch.Count > 0 )
            {                
                drugSetModel.currentDisplayDrug = myBrandSearch.First();
                
                resultInfo.AddRange(myBrandSearch.Select(x => x.DrugBrand).ToList());
                drugSetModel.userDrugInfoArray = resultInfo.ToArray();
            }
            else if(myGenericSearch.Count>0)
            {
                drugSetModel.currentDisplayDrug = myGenericSearch.First();

                resultInfo.AddRange(myGenericSearch.Select(x => x.DrugBrand).ToList());
                drugSetModel.userDrugInfoArray = resultInfo.ToArray();
            }

            return PartialView("_FlashMyCard", drugSetModel);
        }
    }
}

Views/FlashCard/Index.cshtml
@model DemoMVC.Models.FlashDrugSetModel

@section header
{
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
}

@{
    ViewBag.Title = "Common drug flash cards";
}

<h2>Drug Flash Card Set</h2>


<div class="container">
    @using (Ajax.BeginForm("DrugSearch", "FlashCard", new AjaxOptions() { UpdateTargetId = "searchResult", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }))
    {
        @Html.AntiForgeryToken()

        <div class="col-md-3">
            <div><b>Drug: </b></div>
            <div>@Html.TextBox("term", null, new { id = "searchTxt" })</div>

            <div><input type="submit" id="searchButton" name="searchButton" value="Search" /></div>

            @{
                List<SelectListItem> dropDownListItems = new List<SelectListItem>();
            
                foreach (var item in ViewBag.myDrugTypes)
                {
                    dropDownListItems.Add(new SelectListItem { Text = item, Value = item });
                }
            }

            <hr />
            <div>@Html.DropDownList("DrugType", dropDownListItems, "Select Drug Type")</div>
                
            </div>
            <div class="col-sm-9">
                <div id="searchResult">

                </div>
            </div>
        }
</div>

<hr />

@using (Ajax.BeginForm("FlashMyCard", "FlashCard", new AjaxOptions() { UpdateTargetId = "updateRegion", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }))
{ 
    @Html.AntiForgeryToken()

    <div id="updateRegion">
        @Html.Partial("_FlashMyCard", Model)
    </div>
    
    <input type="submit" name="submit" value="Previous" />
    <input type="submit" name="submit" value="Next" />
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")﻿
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")﻿
    <script src="~/Scripts/jquery-ui.js"></script>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#searchTxt").autocomplete({
            source: '@Url.Action("GetSearchDrugs")'
        });
    });

    $(document).ready($('#DrugType').change(function () {
        var selectedOption = $('#DrugType').val();

        $.ajax({
            url: '@Url.Action("DrugTypeSearch")',
            type: "GET",
            data: { 'drugTypeSearch': $(this).val() },
            dataType: "html",
            success: function(result) { $('#searchResult').html(result); },
            error: function(error) { alert(error); }
        } );
    }));

    $(document).ready($('#searchButton').click(function(){$('#DrugType').get(0).selectedIndex = 0;}));
</script>

Views/FlashCard/Indexs.cshtml
@model DemoMVC.Models.FlashDrugSetModel

@section header
{
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
}

@{
    ViewBag.Title = "Common drug flash cards";
}

<h2>Drug Flash Card Set</h2>


<div class="container">
    @using (Ajax.BeginForm("DrugSearch", "FlashCard", new AjaxOptions() { UpdateTargetId = "searchResult", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }))
    {
        @Html.AntiForgeryToken()

        <div class="col-md-3">
            <div><b>Drug: </b></div>
            <div>@Html.TextBox("term", null, new { id = "searchTxt" })</div>

            <div><input type="submit" id="searchButton" name="searchButton" value="Search" /></div>

            @{
                List<SelectListItem> dropDownListItems = new List<SelectListItem>();
            
                foreach (var item in ViewBag.myDrugTypes)
                {
                    dropDownListItems.Add(new SelectListItem { Text = item, Value = item });
                }
            }

            <hr />
            <div>@Html.DropDownList("DrugType", dropDownListItems, "Select Drug Type")</div>
                
            </div>
            <div class="col-sm-9">
                <div id="searchResult">

                </div>
            </div>
        }
</div>

<hr />

@using (Ajax.BeginForm("FlashMyCard", "FlashCard", new AjaxOptions() { UpdateTargetId = "updateRegion", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }))
{ 
    @Html.AntiForgeryToken()

    <div id="updateRegion">
        @Html.Partial("_FlashMyCard", Model)
    </div>
    
    <input type="submit" name="submit" value="Previous" />
    <input type="submit" name="submit" value="Next" />
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")﻿
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")﻿
    <script src="~/Scripts/jquery-ui.js"></script>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#searchTxt").autocomplete({
            source: '@Url.Action("GetSearchDrugs")'
        });
    });

    $(document).ready($('#DrugType').change(function () {
        var selectedOption = $('#DrugType').val();

        $.ajax({
            url: '@Url.Action("DrugTypeSearch")',
            type: "GET",
            data: { 'drugTypeSearch': $(this).val() },
            dataType: "html",
            success: function(result) { $('#searchResult').html(result); },
            error: function(error) { alert(error); }
        } );
    }));

    $(document).ready($('#searchButton').click(function(){$('#DrugType').get(0).selectedIndex = 0;}));
</script>

Views/FlashCard/_FlashACard.cshtml
@model DemoMVC.Classes.Drug

<div>
    <h4>FlashADrugModel</h4>    
</div>

<div>
    <h4>Drug</h4>
    <hr />
    <div class="displayFront">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(m => m.DrugBrand)
            </dt>

            <dd>
                @Html.DisplayFor(m => m.DrugBrand)
            </dd>
        </dl>
    </div>

    <div class="displayBack">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(m => m.DrugType)
            </dt>

            <dd>
                @Html.DisplayFor(m => m.DrugType)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.DrugGeneric)
            </dt>

            <dd>
                @Html.DisplayFor(m => m.DrugGeneric)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.Action)
            </dt>

            <dd>
                @Html.DisplayFor(m => m.Action)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.Therapeutic)
            </dt>

            <dd>
                @Html.DisplayFor(m => m.Therapeutic)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.Indication)
            </dt>

            <dd>
                @Html.DisplayFor(m => m.Indication)
            </dd>

        </dl>
    </div>
</div>

<script src="~/Scripts/jquery-2.1.3.js"></script>
<script type="text/javascript">
    $('.displayBack').hide();
    $('.displayFront, .displayBack').on('click',
                              function () {
                                  $('.displayFront, .displayBack').toggle()
                              }
                           );
</script>

Views/FlashCard/_FlashCards.cshtml
@model DemoMVC.Classes.Drug



<div>
    <h4>Drug</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DrugType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DrugType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DrugGeneric)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DrugGeneric)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DrugBrand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DrugBrand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Action)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Therapeutic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Therapeutic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Indication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Indication)
        </dd>

    </dl>
</div>


@{
    int item = 0;

    int b = 1;
}

Views/FlashCard/_FlashMyCard.cshtml
@model DemoMVC.Models.FlashDrugSetModel
<link href="~/Content/flash-card.css" rel="stylesheet" />
<div>
    <h4>Drug Card[s]</h4>
    <hr />
    <div class="displayFront">
        <div class="displayContent">
            <span>
                <b>@Html.DisplayNameFor(m => m.currentDisplayDrug.DrugBrand)</b>: 

                @Html.DisplayFor(m => m.currentDisplayDrug.DrugBrand)
                @Html.HiddenFor(m => m.currentDisplayDrug.DrugBrand)
            </span>
        </div>
    </div>

    <div class="displayBack">
        <div class="displayContent">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(m => m.currentDisplayDrug.DrugType)
                </dt>

                <dd>
                    @Html.DisplayFor(m => m.currentDisplayDrug.DrugType)
                    @*@Html.HiddenFor(m => m.currentDisplayDrug.DrugType)*@
                </dd>

                <dt>
                    @Html.DisplayNameFor(m => m.currentDisplayDrug.DrugGeneric)
                </dt>

                <dd>
                    @Html.DisplayFor(m => m.currentDisplayDrug.DrugGeneric)
                    @*@Html.HiddenFor(m => m.currentDisplayDrug.DrugGeneric)*@
                </dd>

                <dt>
                    @Html.DisplayNameFor(m => m.currentDisplayDrug.Action)
                </dt>

                <dd>
                    @Html.DisplayFor(m => m.currentDisplayDrug.Action)
                    @*@Html.HiddenFor(m => m.currentDisplayDrug.Action)*@
                </dd>

                <dt>
                    @Html.DisplayNameFor(m => m.currentDisplayDrug.Therapeutic)
                </dt>

                <dd>
                    @Html.DisplayFor(m => m.currentDisplayDrug.Therapeutic)
                    @*@Html.HiddenFor(m => m.currentDisplayDrug.Therapeutic)*@
                </dd>

                <dt>
                    @Html.DisplayNameFor(m => m.currentDisplayDrug.Indication)
                </dt>

                <dd>
                    @Html.DisplayFor(m => m.currentDisplayDrug.Indication)
                    @*@Html.HiddenFor(m => m.currentDisplayDrug.Indication)*@
                </dd>

            </dl>
        </div>
    </div>
</div>

@Html.HiddenFor(x => x.currentArrayIndex)

@for(int i =0;i<Model.userDrugInfoArray.Length;i++) 
{
    @Html.HiddenFor(x => x.userDrugInfoArray[i])
}

<script src="~/Scripts/jquery-2.1.3.js"></script>
<script type="text/javascript">
    $('.displayBack').hide();
    $('.displayFront, .displayBack').on('click',
                              function ()
                              {
                                  $('.displayFront, .displayBack').toggle()
                              }
                           );
</script>

Views/FlashCard/_SearchDrugsResult.cshtml
@model DemoMVC.Models.SearchDrugsModel

<div>
    <h4>Search Result[s]</h4>
    <hr />

    <div class="container">
        @foreach (var item in Model.searchDrugsResult.Select((model, index) => new { index, model }))
        {
            <div class="col-sm-4">
                <div>@Ajax.ActionLink(@item.model, "FlashACard", "FlashCard", new { wantedDisplayDrug = @item.model}, new AjaxOptions{UpdateTargetId = "updateRegion"})</div>
            </div>            
        }
    </div>

</div>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")﻿
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")﻿
    <script src="~/Scripts/jquery-ui.js"></script>
}