Models/TankDurationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoMVC.Models
{
    public class TankDurationViewModel
    {
        [Required]
        
        [Range(typeof(decimal),"0.01","99999")]
        public int gauge_pressure_psi { get; set; }
        [Required]
        [Range(typeof(decimal), "0.01", "99999")]
        public int liter_flow_L { get; set; }
        
        public decimal selectedTankFactor { get;set; }
        public List<SelectListItem> tank_factor_list { get; set; }

        public double? myAnswer { get; set; }

        public TankDurationViewModel()
        {
            this.tank_factor_list = new List<SelectListItem>();
            this.tank_factor_list.Add(new SelectListItem { Text = "E", Value = "0.28" });
            this.tank_factor_list.Add(new SelectListItem { Text = "H", Value = "3.14" });
        }
    }
}

Controllers/RespiratoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoMVC.Respiratory;
using DemoMVC.Classes;
using Ninject;
using DemoMVC.Models;
using SimpleMathExpression;
using DemoMVC.Loggers;

namespace DemoMVC.Controllers
{
    public class RespiratoryController : Controller
    {
        private ICacheProvider Cache;
        private IReadEquationData<Equation> ReadEquationData;
        private IMathExpressionParser MathExpressionParser;
        private IMyLogger myLogger;

        public RespiratoryController([Named("FileDependency")]ICacheProvider cache, IReadEquationData<Equation> readEquationData,IMathExpressionParser mathExpressionParser,IMyLogger logger)
        {
            this.myLogger = logger;
            this.Cache = cache;
            this.ReadEquationData = readEquationData;
            this.MathExpressionParser = mathExpressionParser;
        }
        public ActionResult ACLSNotes()
        {
            return View();
        }
        // GET: Respiratory
        public ActionResult TankDuration()
        {
            TankDurationViewModel model = new TankDurationViewModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult TankDuration(TankDurationViewModel input_model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Duration(in minutes) = (gauge_pressure(psi) * tank_factor) / liter_flow
                    EquationsRepository equationRespository = new EquationsRepository(Cache, ReadEquationData);
                    Equation requestedEquation = equationRespository.GetAnEquation("Tank_Oxygen_Duration");

                    if (requestedEquation != null)
                    {
                        string myEquationExpression = requestedEquation.EquationExpression;
                        double myAnswer = 0;
                        string error = string.Empty;

                        //Substitute my variable in equation with value from user.

                        myEquationExpression = myEquationExpression.Replace("tank_factor", input_model.selectedTankFactor.ToString());
                        myEquationExpression = myEquationExpression.Replace("gauge_pressure_psi", input_model.gauge_pressure_psi.ToString());
                        myEquationExpression = myEquationExpression.Replace("liter_flow_L", input_model.liter_flow_L.ToString());


                        if(MathExpressionParser.SolveExpression(myEquationExpression,out myAnswer,out error))
                        {
                            input_model.myAnswer = myAnswer;
                        }
                        else
                        {
                            myLogger.Error("Error using SimpleCalculatorService: "+ error);
                            return View("Error");
                        }
                        //DemoMVC.SimpleCalcServiceConsoleHost.CalculatorClient calculatorClient = new SimpleCalcServiceConsoleHost.CalculatorClient();

                        //try
                        //{
                        //    myAnswer = calculatorClient.SolveExpression(myEquationExpression);
                        //    input_model.myAnswer = double.Parse(myAnswer);
                        //    // More code that isn't useful including here ...
                            
                        //}
                        //catch (Exception e)
                        //{
                        //    ErrorSignal.FromCurrentContext().Raise(e);
                        //    //logger.Error("Error using SimpleCalculatorService.", e);
                        //}
                        //finally
                        //{
                        //    calculatorClient.Close();
                        //}
                    }

                }
                catch (Exception ex)
                {
                    myLogger.Error("Error using SimpleCalculatorService: ",ex);
                    return View("Error");
                    //ErrorSignal.FromCurrentContext().Raise(ex);
                }
            }


            return View(input_model);
        }

        public ActionResult ListRespiratoryEquations()
        {
            EquationsRepository equationRespository = new EquationsRepository(Cache, ReadEquationData);

            List<Equation> equationList =  equationRespository.GetAllEquations();

            return View(equationList);
        }
        public ActionResult EquationGeneratorForm(string abbreviation)
        {
            EquationsRepository equationRespository = new EquationsRepository(Cache, ReadEquationData);
            Equation requestedEquation = equationRespository.GetAnEquation(abbreviation);
            EquationAnswerViewModel equationAnswerViewModel = new EquationAnswerViewModel();
            if(requestedEquation!=null)
            {
                equationAnswerViewModel.myEquation = requestedEquation;
            }

            return View(equationAnswerViewModel);
        }

        [HttpPost]
        public ActionResult EquationGeneratorForm(FormCollection collection)
        {
            string equationQuery = string.Empty;
            string equation = string.Empty;
            double answer = 0;
            string error = string.Empty;

            EquationAnswerViewModel equationAnswerViewModel = new EquationAnswerViewModel();            
            EquationsRepository equationRespository = new EquationsRepository(Cache, ReadEquationData);

            if (collection.AllKeys.Contains("abbreviation"))
            {
                equationQuery = collection["abbreviation"];

                Equation requestedEquation = equationRespository.GetAnEquation(equationQuery);

                if (requestedEquation != null)
                {
                    equation = requestedEquation.EquationExpression;
                    equationAnswerViewModel.myEquation = requestedEquation;
                }

                //Substitute my variable in equation with value from user.
                foreach (string key in collection.Keys)
                {
                    string tmp = collection[key];

                    if (equation.Contains(key))
                    {
                        equation = equation.Replace(key, tmp);
                        if (equationAnswerViewModel.myCollection==null)
                        {
                            equationAnswerViewModel.myCollection = new Dictionary<string, string>();
                        }
                        equationAnswerViewModel.myCollection.Add(key, tmp);
                    }
                }
                

                if (MathExpressionParser.SolveExpression(equation, out answer, out error))
                {
                    equationAnswerViewModel.myAnswer = answer;
                }
                else
                {
                    myLogger.Error("Error using SimpleCalculatorService: "+error);
                    return View("Error");
                }

                //DemoMVC.SimpleCalcServiceConsoleHost.CalculatorClient calculatorClient = new SimpleCalcServiceConsoleHost.CalculatorClient();
                
                
                //try
                //{
                //    answer = calculatorClient.SolveExpression(equation);
                //    equationAnswerViewModel.myAnswer = double.Parse(answer);
                //    // More code that isn't useful including here ...
                    
                //}
                //catch (Exception e)
                //{
                //    ErrorSignal.FromCurrentContext().Raise(e);
                //    //logger.Error("Error using SimpleCalculatorService.", e);
                //}
                //finally
                //{
                //    calculatorClient.Close();
                //}


            }
            else
            {
                myLogger.Error("Key not found.");
                return View("Error");
            }

            return View(equationAnswerViewModel);
        }
    }
}

Views/Respiratory/ACLSNotes.cshtml
@{
    ViewBag.Title = "ACLSNotes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ACLSNotes</h2>


<img src="~/Respiratory/images/220px-beating-heart-animation-197679.gif" />

<div>Is it safe to approach?</div>
<div>
    1. Assess the victim's responsiveness.
    <div class="question">Tap the victim’s shoulder and shout “Are you okay?”</div>
    <div class="answer">I'm ok
        <div>Just checking to see if you ok. Bye.</div>
    </div>
    <div class="answer">No response.
        <div class="observation">Check to see if the victim is breathing by looking at their chest. If they are not breathing, or not breathing normally (only gasping), call 911.</div>
    </div>
</div>

<div>    
    2. Activate EMS (Emergency Medical Response) by calling 911.
</div>

<div>
    3. Retrieve a defibrillator, usually an automatic external defibrillator (AED).
</div>

<div>
    4. The algorithm proceeds in a loop of CPR and rhythm checks with defibrillation.
</div>

<div>
    5. Check PULSE before chest compressions for at least five seconds and no more than ten seconds.
</div>

<div>
    6.  CPR: push hard and fast. Begin chest compressions before ventilation. Chest compressions allow blood flow to the heart and brain. Delays in chest compressions result in diminished survival.
</div>

<div>
    7. For effective breathing, watch for chest rise and avoid excessive ventilation. 10 to 12 BREATHS should be delivered each minute, or one breath every five to six seconds. Each breath should be delivered over 1 second. Observe visible chest rise.
</div>

<div>
    Avoid gastric inflation, as it may result in aspiration, pneumonia or vomiting.
</div>

<div>
    8. The ratio of chest compressions to breaths is 30 to 2.
</div>

<div>
    9. Recheck the patient every five cycles (of 30:2).
</div>

<div>
    10.   After the defibrillator becomes available, check rhythm. USE THE AED WHEN INDICATED AND AVAILABLE.  The victim should receive a shock that is repeated every two minutes or 5 cycles.
</div>

"Look, listen, and feel" is no longer part of the BLS algorithm. The emphasis is on high quality CPR.

Views/Respiratory/EquationGeneratorForm.cshtml
@model DemoMVC.Models.EquationAnswerViewModel

@{
    ViewBag.Title = "Equation Generator Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.myEquation.Id</h2>
<h4>@Model.myEquation.Description</h4>
<h4>@Model.myEquation.EquationExpression</h4>

<div class="container">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();

        <div class="form-horizontal"><hr />
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @{
        string[] splitExpression = Model.myEquation.EquationExpression.Split(new Char[] { '(', ')', '+', '-', '*', '/', '^', '%' });

            List<string> inputList = new List<string>();
            <input type="hidden" name="abbreviation" value="@Model.myEquation.Abbreviation" />            
            
            foreach (string input in splitExpression)
            {
                if (input.Trim() != "")
                {
                    //duplication?
                    if (!inputList.Contains(input))
                    {
                        float fResult = 0;
                        //don't want numbers
                        if (!float.TryParse(input, out fResult))
                        {
                            inputList.Add(input);

                            <div class="form-group">
                                <div class="col-md-2 control-label">
                                    <label for="@input">@input</label>
                                </div>
                                <div class="col-md-10">
                                    @{
                                        string myValue = "";
                            
                                        if(Model.myCollection!=null)
                                        { 
                                            if(Model.myCollection.ContainsKey(input))
                                            {
                                                myValue = Model.myCollection[input];
                                            }
                                        }
}
                                    
                                    <input type="number" name="@input" value="@myValue" placeholder="@input" step="0.01" required />
                                </div>
                            </div>
                        }
                    }
                }
            }

            if(Model.myAnswer.HasValue)
            {
            <hr />
            <div class="form-group">
                <div class="col-md-2 control-label">
                    <label for="answert">Answer</label>
                </div>
                <div class="col-md-10">
                    <input type="number" name="answer" id="answer" value="@Model.myAnswer" placeholder="Answer" step="0.01" readonly />
                </div>
            </div>
        }
}
    
    

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" id="submit" class="btn btn-default" />
                </div>
            </div>
        </div>
        
    }

</div>

<div>
    @Html.ActionLink("List Equations", "ListRespiratoryEquations", "Respiratory")
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")﻿
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")﻿
}

@*<script>
    $(document).ready(function(){
        $("#submit").click(function (e) {
                e.preventDefault();

                $.ajax({
                    url: '@Url.Action("CalcEquationForm")',
                    type: "GET",
                    data: { id: $("Shareitem").val(), access_token: $("access_token").val() },
                    success: function (result) {
                    $("sharelink").html(result);

        }});
      });
    });
    </script>*@

Views/Respiratory/InitialVentSettings.cshtml
  <form id="Form1" >
    <div class="container">
        <div class="jumbotron">
            <fieldset class="responsive-fieldset">
                <legend>Initial Ventilator Settings Calculator</legend>
                <div class="container">
                    <div class="row" align="center">
                        <div class="col-md-2">
                            <DropDownList ID="DropDownListM_F" >
                                <listitem text="Male" value="Male"></listitem>
                                <listitem text="Female" value="Female"></listitem>
                            </DropDownList>
                        </div>
                        <div class="col-md-2">
                            <TextBox ID="TextBoxHeight"  Width="75"></TextBox>
                        </div>

                        <div class="col-md-2">
                            <RequiredFieldValidator ID="RequiredFieldValidator1" 
                                                        ErrorMessage="RequiredFieldValidator" ControlToValidate="TextBoxHeight"></RequiredFieldValidator>
                        </div>
                        <div class="col-md-2">
                            <DropDownList ID="DropDownListInchesOrCm" >
                                <listitem text="inches" value="inches"></listitem>
                                <listitem text="cm" value="cm"></listitem>
                            </DropDownList>
                        </div>
                        <div class="col-md-2">Ideal Body Weight</div>
                        <div class="col-md-2">
                            <Label ID="LabelIBW"  Text="IBW"></Label>
                        </div>
                    </div>
                    <div class="row" align="center">
                        <div class="col-md-2">
                            &nbsp;
                        </div>
                        <div class="col-md-2">
                            1 ft = 12 inches
                        </div>
                        <div class="col-md-2">1 inch = 2.54 cm</div>
                        <div class="col-md-2">
                            &nbsp;
                        </div>
                        <div class="col-md-2">
                            &nbsp;
                        </div>
                        <div class="col-md-2">
                            &nbsp;
                        </div>
                    </div>
                    <div class="row" align="center">
                        <div class="col-md-12">&nbsp;</div>
                    </div>
                    <div class="row" align="center">
                        <div class="col-md-12">
                            <Button ID="ButtonAnalyze"  Text="Solve" OnClick="ButtonAnalyze_Click" />
                        </div>
                    </div>
                    <div class="row" align="center">
                        <div class="col-md-12">
                            <Label ID="LabelErrorMsg" ></Label>
                            &nbsp;
                        </div>
                    </div>
                    <Panel ID="PanelVentTable"  Visible="False">
                        <div class="table-responsive" id="ventTable">
                            <table class="table">
                                <tr>
                                    <th>
                                        5mL/kg
                                    </th>
                                    <th>
                                        6mL/kg
                                    </th>
                                    <th>
                                        7mL/kg
                                    </th>
                                    <th>
                                        8mL/kg
                                    </th>
                                    <th>
                                        9mL/kg
                                    </th>
                                    <th>
                                        10mL/kg
                                    </th>
                                </tr>
                                <tr>
                                    <td>
                                        <Label ID="Label5ml"  Text=""></Label>
                                    </td>
                                    <td>
                                        <Label ID="Label6ml"  Text=""></Label>
                                    </td>
                                    <td>
                                        <Label ID="Label7ml"  Text=""></Label>
                                    </td>
                                    <td>
                                        <Label ID="Label8ml"  Text=""></Label>
                                    </td>
                                    <td>
                                        <Label ID="Label9ml"  Text=""></Label>
                                    </td>
                                    <td>
                                        <Label ID="Label10ml"  Text=""></Label>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </Panel>
                </div>
            </fieldset>
        </div>
    </div>
</form>

Views/Respiratory/Intubation_CheckList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


Preparation
Equipments
Drugs
Patient-Prep
Post-Intubation Care

Views/Respiratory/ListRespiratoryEquations.cshtml
@model IEnumerable<DemoMVC.Classes.Equation>

@{
    ViewBag.Title = "Respiratory Equations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of respiratory equations</h2>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <h3>Abbreviation</h3>
        </div>
        <div class="col-md-6">
            <h3>Equation</h3>
        </div>
        <div class="col-md-4">
            <h3>Equation</h3>
        </div>
        <br /><br />
        @foreach (var item in Model)
        {
            <div class="col-md-2">
                @Html.ActionLink(item.Abbreviation, "EquationGeneratorForm", "Respiratory", new { abbreviation = item.Abbreviation }, null)
            </div>
            <div class="col-md-6">
                @Html.DisplayFor(modelItem => item.Description)
            </div>
            <div class="col-md-4">
                @Html.DisplayFor(modelItem => item.EquationExpression)
            </div>
            <br /><br />
        }
    </div>
</div>

Views/Respiratory/RespiratoryEquationForm.cshtml
@{
    ViewBag.Title = "RespiratoryEquationForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RespiratoryEquationForm</h2>

<br />
@TempData["user_equation"];

Views/Respiratory/TankDuration.cshtml
@model DemoMVC.Models.TankDurationViewModel

@{
    ViewBag.Title = "TankDuration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TankDuration</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TankDurationViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.gauge_pressure_psi, "Guage Pressure (psi)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gauge_pressure_psi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gauge_pressure_psi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.liter_flow_L, "Liter Flow (L)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.liter_flow_L, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.liter_flow_L, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2"></div>
            <div class="col-md-10">
                @Html.DropDownListFor(x=>x.selectedTankFactor,Model.tank_factor_list,"Tank Type")                
                @Html.ValidationMessageFor(model => model.selectedTankFactor, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            if(Model.myAnswer.HasValue)
            {
            <hr />
            <div class="form-group">
                <div class="col-md-2 control-label">
                    <label for="answert">Answer</label>
                </div>
                <div class="col-md-10">
                    <input type="number" name="answer" id="answer" value="@Model.myAnswer" placeholder="Answer" step="0.01" readonly />
                </div>
            </div>
            }
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")﻿
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")﻿
}

Views/Respiratory/inputGenTest.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-4">1</div>
<div class="col-md-4">2</div>
<div class="col-md-4">3</div>
<div class="col-md-4">4</div>
<div class="col-md-4">5</div>
<div class="col-md-4">6</div>
<div class="col-md-4">7</div>
<div class="col-md-4">8</div>
<div class="col-md-4">9</div>
<div class="col-md-4">10</div>
<div class="col-md-4">11</div>
<div class="col-md-4">12</div>
<div class="col-md-4">13</div>
<div class="col-md-4">14</div>
<div class="col-md-4">15</div>